// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My.Project.adk.DbFolder;

namespace My.Project.adk.Migrations
{
    [DbContext(typeof(DbProject))]
    partial class DbProjectModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("My.Project.adk.Models.Classe", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnneeScolaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Niveau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sexe")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EcoleID");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("My.Project.adk.Models.Ecole", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ecole");
                });

            modelBuilder.Entity("My.Project.adk.Models.Eleve", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClasseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateNaissaince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postnom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sexe")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClasseID");

                    b.ToTable("Eleve");
                });

            modelBuilder.Entity("My.Project.adk.Models.Classe", b =>
                {
                    b.HasOne("My.Project.adk.Models.Ecole", "Ecole")
                        .WithMany("Classes")
                        .HasForeignKey("EcoleID");

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("My.Project.adk.Models.Eleve", b =>
                {
                    b.HasOne("My.Project.adk.Models.Classe", "Classe")
                        .WithMany("Eleve")
                        .HasForeignKey("ClasseID");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("My.Project.adk.Models.Classe", b =>
                {
                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("My.Project.adk.Models.Ecole", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
